# Generated by Django 2.2.7 on 2019-11-24 06:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog1', '0002_auto_20191123_1956'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-created_time'], 'verbose_name': '文章', 'verbose_name_plural': '文章'},
        ),
    ]
